# Generated by Django 3.2.8 on 2021-11-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('test', 'test permission')], max_length=250)),
                ('role', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('type', models.CharField(max_length=250)),
                ('author', models.ManyToManyField(through='gestion_projet.Contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contributors',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.projets'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
