# Generated by Django 3.2.8 on 2021-11-14 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projets',
            name='author',
        ),
        migrations.AddField(
            model_name='projets',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
