# Generated by Django 3.2.8 on 2021-11-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0003_alter_projets_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projets',
            old_name='user',
            new_name='author',
        ),
    ]
