# Generated by Django 3.2.8 on 2021-12-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contributors',
            options={'verbose_name': 'Contributor', 'verbose_name_plural': 'Contributors'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
