# Generated by Django 3.2.8 on 2021-12-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_projet', '0008_auto_20211213_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('1', 'author'), ('2', 'contributor')], max_length=250),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrib', to=settings.AUTH_USER_MODEL),
        ),
    ]
